// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv4Mmmga3R5RvVgZD3zeN2c9qDF4YFPr8',
    appId: '1:209151491128:web:d8cb992d99b3594b9afacd',
    messagingSenderId: '209151491128',
    projectId: 'callingapp-saas',
    authDomain: 'callingapp-saas.firebaseapp.com',
    databaseURL: 'https://callingapp-saas-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'callingapp-saas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb91yw8mUmM0GQ7bcC0ykIy-vxoiRhJJs',
    appId: '1:209151491128:android:326c07cff6253ef19afacd',
    messagingSenderId: '209151491128',
    projectId: 'callingapp-saas',
    databaseURL: 'https://callingapp-saas-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'callingapp-saas.firebasestorage.app',
  );
}
